apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: {{ (index .Values.ingress.paths 0).path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ (index .Values.ingress.paths 0).serviceName }}
                port:
                  number: {{ (index .Values.ingress.paths 0).servicePort }}
