image:
  tag: prod-latest

replicas: 2
containerPort: 8080

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  paths:
    - path: /api/<SHORTENED APP NAME>/(.*)
      serviceName: <APP NAME>-prod-service
      servicePort: 80
